const actions = {
    ADD_USER: "ADD_USER",
    TOGGLE_REQUEST: "TOGGLE_REQUEST",
    GET_REQUEST: "GET_REQUEST",
    TOGGLE_FRIEND: "TOGGLE_FRIEND",
    GET_MY_FRIEND: "GET_MY_FRIEND",
    SEND_MESSAGE: "SEND_MESSAGE",
    GET_MESSAGE: "GET_MESSAGE",
};

export default actions;
